name: Create Branch and Pull Request

on:
  issues:
    types: [opened]

jobs:
  create-branch-and-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Branch and Comment on Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const issueTitle = context.issue.title;
            const branchName = `issue-${issueNumber}-${issueTitle.replace(/\s/g, '_')}`;
            git checkout -b "$branchName";
            git push origin "$branchName";

            core.issue.createComment({
              issue_number: issueNumber,
              body: `This branch (${branchName}) has been created for this issue.`
            });
