name: Create Branch and Pull Request

on:
  issues:
    types: [opened]

jobs:
  create-branch-and-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Branch and Comment on Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const issueTitle = context.issue.title;
            const branchName = `issue-${issueNumber}-${issueTitle.replace(/\s/g, '_')}`;
            git checkout -b "$branchName";
            git push origin "$branchName";

            core.issue.createComment({
              issue_number: issueNumber,
              body: `This branch (${branchName}) has been created for this issue.`
            });

      - name: Link Branch to Issue
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"This branch has been created for this issue. You can view the pull request [here]($GITHUB_SERVER_URL/${{ github.repository }}/pull/${{ env.BRANCH_NAME }}).\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.issue_number }}/comments"